spring:
  profiles:
    active: test
  application:
    name: boot-jpa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085
  context-path: /boot-jpa
logging:
  exception-conversion-word: '%wEx'
  path: F:\tel\spring-boot\log
  level:
    root: info