spring:
  application:
    name: boot-redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 500
      min-idle: 0
    timeout: 0
server:
  port: 8084
  context-path: /boot-redis
logging:
  exception-conversion-word: '%wEx'
  path: F:\tel\spring-boot\log
  level:
    root: info
