spring:
  application:
    name: boot-form
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8085
  context-path: /boot-form
logging:
  exception-conversion-word: '%wEx'
  path: F:\tel\spring-boot\log
  level:
    root: info